name: campuslink
description: CampusLink - Your campus community app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Navigation
  go_router: ^13.2.0

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # HTTP client
  # dio: ^5.4.3+1
  dio: ^5.4.0

  # Secure storage (tokens + PIN)
  flutter_secure_storage: ^9.2.2

  # Biometrics
  local_auth: ^2.3.0

  # Image picker (avatar, listings)
  image_picker: ^1.2.2

  # File picker (documents)
  # file_picker: ^8.0.3

  flutter_pdfview: ^1.4.4
  path_provider: ^2.1.6
  

  # WebSocket (chat)
  web_socket_channel: ^3.0.1

  # Shared preferences (theme, settings)
  shared_preferences: ^2.2.3

  # JSON serialization
  json_annotation: ^4.9.0

  # UI extras
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  pinput: ^5.0.0
  url_launcher: ^6.3.2
  record: ^7.1.0
  just_audio: ^0.10.5
  permission_handler: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true